export const PERMISSION_EFFECTS = [
  "READ",
  "CREATE",
  "UPDATE",
  "OPERATE",
  "SUBMIT",
  "APPROVE",
  "EXPORT_REQUEST",
  "EXPORT_SETTLE",
  "ACCESS_ADMIN",
  "TECHNICAL_ADMIN",
  "IMPERSONATE",
] as const;

export const PERMISSION_SCOPES = [
  "ORGANISATION",
  "CLIENT",
  "EVENT",
  "DEPARTMENT",
  "SELF",
  "TECHNICAL_SERVICE",
] as const;

export const ROLE_KEYS = [
  "CEO",
  "EVENT_DIRECTOR",
  "PLANNER",
  "CLIENT_LEAD",
  "DEPARTMENT_LEAD",
  "SYSTEM_ADMINISTRATOR",
  "READ_ONLY_AUDITOR",
  "RISK_GOVERNANCE_REVIEWER",
] as const;

export type PermissionEffect = (typeof PERMISSION_EFFECTS)[number];
export type PermissionScope = (typeof PERMISSION_SCOPES)[number];
export type RoleKey = (typeof ROLE_KEYS)[number];

export interface PermissionDefinition {
  description: string;
  effect: PermissionEffect;
  scope: PermissionScope;
  permittedRoles: readonly RoleKey[];
  mutates: boolean;
  externalEffect: boolean;
  ceoReserved: boolean;
  technicalOnly: boolean;
  makerChecker: boolean;
}

const ALL_ROLES = ROLE_KEYS;
const READ_ROLES = [
  "CEO",
  "EVENT_DIRECTOR",
  "PLANNER",
  "CLIENT_LEAD",
  "DEPARTMENT_LEAD",
  "SYSTEM_ADMINISTRATOR",
  "READ_ONLY_AUDITOR",
  "RISK_GOVERNANCE_REVIEWER",
] as const satisfies readonly RoleKey[];

export const PERMISSION_REGISTRY = {
  "organisation.view": {
    description: "View the organisation summary for an active membership",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "organisation.manage": {
    description: "Edit organisation legal identity, display name and status",
    effect: "UPDATE",
    scope: "ORGANISATION",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.list": {
    description: "List clients visible inside the actor's scope",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: [
      "CEO",
      "EVENT_DIRECTOR",
      "PLANNER",
      "CLIENT_LEAD",
      "SYSTEM_ADMINISTRATOR",
      "READ_ONLY_AUDITOR",
      "RISK_GOVERNANCE_REVIEWER",
    ],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.view": {
    description: "View one client",
    effect: "READ",
    scope: "CLIENT",
    permittedRoles: [
      "CEO",
      "EVENT_DIRECTOR",
      "PLANNER",
      "CLIENT_LEAD",
      "SYSTEM_ADMINISTRATOR",
      "READ_ONLY_AUDITOR",
      "RISK_GOVERNANCE_REVIEWER",
    ],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.create": {
    description: "Create a client inside the organisation",
    effect: "CREATE",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.update": {
    description: "Correct client identity and status",
    effect: "UPDATE",
    scope: "CLIENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER", "CLIENT_LEAD"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.archive": {
    description: "Archive a client without deleting it",
    effect: "OPERATE",
    scope: "CLIENT",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "client.restore": {
    description: "Restore an archived client to active use",
    effect: "OPERATE",
    scope: "CLIENT",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "programme.list": {
    description: "List event programmes for a client",
    effect: "READ",
    scope: "CLIENT",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "programme.view": {
    description: "View one event programme",
    effect: "READ",
    scope: "CLIENT",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "programme.create": {
    description: "Create an optional event programme grouping",
    effect: "CREATE",
    scope: "CLIENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "programme.update": {
    description: "Edit an event programme",
    effect: "UPDATE",
    scope: "CLIENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "programme.archive": {
    description: "Archive an event programme",
    effect: "OPERATE",
    scope: "CLIENT",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.list": {
    description: "List events visible inside the actor's scope",
    effect: "READ",
    scope: "EVENT",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.view": {
    description: "View one event",
    effect: "READ",
    scope: "EVENT",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.create": {
    description: "Create an event in Discover",
    effect: "CREATE",
    scope: "CLIENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.update": {
    description: "Edit event facts",
    effect: "UPDATE",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER", "CLIENT_LEAD"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.phase.transition": {
    description: "Move an event through a permitted phase",
    effect: "OPERATE",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "event.archive": {
    description: "Archive an event through the reserved maker/checker decision",
    effect: "APPROVE",
    scope: "EVENT",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: true,
  },
  "event.restore": {
    description: "Restore an archived event",
    effect: "OPERATE",
    scope: "EVENT",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "mef.view": {
    description: "View the Master Event File composition slots",
    effect: "READ",
    scope: "EVENT",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "mef.update": {
    description: "Record a human update to a Master Event File slot",
    effect: "UPDATE",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "department.view": {
    description: "View organisation departments",
    effect: "READ",
    scope: "DEPARTMENT",
    permittedRoles: [
      "CEO",
      "EVENT_DIRECTOR",
      "DEPARTMENT_LEAD",
      "SYSTEM_ADMINISTRATOR",
      "READ_ONLY_AUDITOR",
    ],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "department.manage": {
    description: "Create and change organisation departments",
    effect: "UPDATE",
    scope: "ORGANISATION",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "workstream.view": {
    description: "View event workstreams",
    effect: "READ",
    scope: "EVENT",
    permittedRoles: [
      "CEO",
      "EVENT_DIRECTOR",
      "PLANNER",
      "DEPARTMENT_LEAD",
      "SYSTEM_ADMINISTRATOR",
      "READ_ONLY_AUDITOR",
    ],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "workstream.manage": {
    description: "Create and change event workstreams",
    effect: "UPDATE",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "workstream.operate": {
    description: "Update the operational note of an assigned workstream",
    effect: "OPERATE",
    scope: "DEPARTMENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "DEPARTMENT_LEAD"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "user.view": {
    description: "View the staff directory",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR", "READ_ONLY_AUDITOR"],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "user.invite": {
    description: "Invite a staff identity",
    effect: "ACCESS_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "user.activate": {
    description: "Activate an invited staff identity",
    effect: "ACCESS_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "user.suspend": {
    description: "Suspend a staff identity",
    effect: "ACCESS_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "user.reinstate": {
    description: "Reinstate a suspended staff identity",
    effect: "ACCESS_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "user.deactivate": {
    description: "Deactivate a staff identity",
    effect: "ACCESS_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "assignment.view": {
    description: "View assignments and access history",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: READ_ROLES,
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "assignment.grant": {
    description: "Grant a scoped assignment",
    effect: "ACCESS_ADMIN",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "assignment.suspend": {
    description: "Suspend an assignment",
    effect: "ACCESS_ADMIN",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "assignment.revoke": {
    description: "Revoke an assignment",
    effect: "ACCESS_ADMIN",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "role.view": {
    description: "View the role and permission catalogue",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR", "READ_ONLY_AUDITOR"],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "role.manage": {
    description: "Create a custom role from classified permissions",
    effect: "TECHNICAL_ADMIN",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "SYSTEM_ADMINISTRATOR"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "audit.view": {
    description: "Search and inspect authorised audit history",
    effect: "READ",
    scope: "ORGANISATION",
    permittedRoles: [
      "CEO",
      "EVENT_DIRECTOR",
      "CLIENT_LEAD",
      "DEPARTMENT_LEAD",
      "SYSTEM_ADMINISTRATOR",
      "READ_ONLY_AUDITOR",
      "RISK_GOVERNANCE_REVIEWER",
    ],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "audit.export.request": {
    description: "Request an audit export without settling it",
    effect: "EXPORT_REQUEST",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: false,
  },
  "audit.export.settle": {
    description: "Settle an audit export and produce the evidence file",
    effect: "EXPORT_SETTLE",
    scope: "ORGANISATION",
    permittedRoles: ["CEO"],
    mutates: true,
    externalEffect: false,
    ceoReserved: true,
    technicalOnly: false,
    makerChecker: false,
  },
  "system.health.view": {
    description: "View non-secret system health and release metadata",
    effect: "READ",
    scope: "TECHNICAL_SERVICE",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "SYSTEM_ADMINISTRATOR", "READ_ONLY_AUDITOR"],
    mutates: false,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
  "approval.request": {
    description: "Submit a maker/checker request",
    effect: "SUBMIT",
    scope: "EVENT",
    permittedRoles: ["CEO", "EVENT_DIRECTOR", "PLANNER", "RISK_GOVERNANCE_REVIEWER"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: true,
  },
  "approval.decide": {
    description: "Approve or reject a maker/checker request",
    effect: "APPROVE",
    scope: "ORGANISATION",
    permittedRoles: ["CEO", "RISK_GOVERNANCE_REVIEWER"],
    mutates: true,
    externalEffect: false,
    ceoReserved: false,
    technicalOnly: false,
    makerChecker: true,
  },
  "support.impersonate": {
    description: "Reserved support impersonation. Denied to every role, including the CEO.",
    effect: "IMPERSONATE",
    scope: "ORGANISATION",
    permittedRoles: [],
    mutates: true,
    externalEffect: true,
    ceoReserved: false,
    technicalOnly: true,
    makerChecker: false,
  },
} as const satisfies Record<string, PermissionDefinition>;

export type PermissionKey = keyof typeof PERMISSION_REGISTRY;

export const PERMISSION_KEYS = Object.keys(PERMISSION_REGISTRY) as PermissionKey[];

export const MEF_SLOTS = [
  "CLIENT",
  "DISCOVERY",
  "EVENT_INTELLIGENCE",
  "EVENT_ARCHITECTURE",
  "GUEST_INTELLIGENCE",
  "PROTOCOL_CULTURAL_INTELLIGENCE",
  "VENDOR_RESOURCE_ARCHITECTURE",
  "PRODUCTION_LOGISTICS",
  "COMMAND_CONTROL",
  "LIVE_EVENT",
  "GUEST_DEPARTURE",
  "FOLLOW_UP",
  "POST_EVENT_INTELLIGENCE",
  "KNOWLEDGE",
] as const;

export type MefSlotKey = (typeof MEF_SLOTS)[number];

export const EVENT_PHASES = [
  "DISCOVER",
  "DESIGN",
  "PREPARE",
  "READY",
  "LIVE",
  "CLOSE",
  "LEARN",
] as const;
export type EventPhase = (typeof EVENT_PHASES)[number];

export function assertRegistryComplete(): void {
  const keys = Object.keys(PERMISSION_REGISTRY);
  if (new Set(keys).size !== keys.length) throw new Error("duplicate permission keys");
  for (const key of keys) {
    const entry = PERMISSION_REGISTRY[key as PermissionKey];
    const required = [
      "description",
      "effect",
      "scope",
      "permittedRoles",
      "mutates",
      "externalEffect",
      "ceoReserved",
      "technicalOnly",
      "makerChecker",
    ] as const;
    for (const field of required) {
      if (entry[field] === undefined) throw new Error(`unclassified permission ${key}.${field}`);
    }
    if (!PERMISSION_EFFECTS.includes(entry.effect)) throw new Error(`unknown effect ${key}`);
    if (!PERMISSION_SCOPES.includes(entry.scope)) throw new Error(`unknown scope ${key}`);
    for (const role of entry.permittedRoles) {
      if (!ROLE_KEYS.includes(role)) throw new Error(`unknown role ${role} on ${key}`);
    }
  }
  if (PERMISSION_REGISTRY["support.impersonate"].permittedRoles.length !== 0) {
    throw new Error("impersonation must remain ungranted");
  }
}

export function businessPermissions(): PermissionKey[] {
  return PERMISSION_KEYS.filter(
    (key) => key !== "support.impersonate" && !PERMISSION_REGISTRY[key].technicalOnly,
  );
}

export function permissionsForRole(role: RoleKey): PermissionKey[] {
  return PERMISSION_KEYS.filter((key) =>
    (PERMISSION_REGISTRY[key].permittedRoles as readonly RoleKey[]).includes(role),
  );
}

void ALL_ROLES;
