export {
  PLATFORM_PACKAGE,
  SHARED_PLATFORM_OWNERSHIP,
  FORBIDDEN_PARALLEL_TRUTH,
  PLATFORM_PERSISTENCE_CONTRACT,
  LOCAL_STORE_PRODUCTION_STATUS,
  PRODUCTION_STORE_STATUS,
  SCHEMA_VERSION,
  DEFAULT_TIMEZONE,
  SESSION_COOKIE,
  RSVP_SESSION_COOKIE,
  VENDOR_SESSION_COOKIE,
  MERCHANDISE_GUEST_SESSION_COOKIE,
  STAFF_SESSION_REVOCATION_REASONS,
  STAFF_SESSION_DENIAL_STATUSES,
  type StaffSessionDenialStatus,
  RSVP_ATTENDANCE_INTENTS,
  CORRELATION_HEADER,
  MEF_COMPOSITION_SLOTS,
  EVENT_PHASES,
  PERMISSION_KEYS,
  SYSTEM_ROLE_KEYS,
  CEO_RESERVED_ACTIONS,
  FIELD_QUALITY_STATES,
  GUEST_LIFECYCLE_STATES,
  IDENTITY_RESOLUTION_STATES,
  CANONICAL_INTAKE_MAPPING_VERSION,
  HONORIFICS,
  ADDRESSING_STATUSES,
  ADDRESSING_SOURCES,
  AGE_BANDS,
  CHILD_AGE_BANDS,
  PARTY_TYPES,
  PARTY_MEMBER_ROLES,
  RELATIONSHIP_TYPES,
  RELATIONSHIP_DIRECTIONS,
  RELATIONSHIP_VISIBILITIES,
  RELATIONSHIP_STATUSES,
  COMPANION_ENTITLEMENT_STATUSES,
  RESPONSIBLE_ADULT_SCOPES,
  MSG_CHANNELS,
  MSG_PURPOSES,
  MSG_CAMPAIGN_STATUSES,
  MSG_MESSAGE_STATUSES,
  PROGRAMME_PHASE_TYPES,
  CHECKPOINT_TYPES,
  ARRIVAL_ROUTE_KINDS,
  VEHICLE_CLASSES,
  MERCHANDISE_ITEM_TYPES,
  PARTICIPATION_CHOICES,
  FULFILMENT_STATES,
  FORECAST_MODEL_VERSION,
  DEFAULT_PARAMETER_SET_VERSION,
  PROVISION_DOMAINS,
  FORECAST_CONFIDENCE_LEVELS,
  type StoreProductionStatus,
} from "./constants.js";
export { PlatformError, PLATFORM_ERROR_CODES, publicMessageFor, type PlatformErrorCode } from "./errors.js";
export {
  OrganisationSchema,
  ClientSchema,
  EventRecordSchema,
  PersonSchema,
  MembershipSchema,
  RoleSchema,
  PermissionSchema,
  AssignmentSchema,
  AuditEventSchema,
  MasterEventFileSchema,
  ConsentRecordSchema,
  GuestReferenceSchema,
  ScopeInputSchema,
  CreateClientInputSchema,
  CreateEventInputSchema,
  UpdateEventInputSchema,
  TransitionEventInputSchema,
  GrantAssignmentInputSchema,
  SignInInputSchema,
  AuthenticateStaffInputSchema,
  StaffSessionSchema,
  StaffSessionActorSchema,
  type Organisation,
  type Client,
  type EventRecord,
  type Person,
  type Membership,
  type Role,
  type Permission,
  type Assignment,
  type AuditEvent,
  type MasterEventFile,
  type ConsentRecord,
  type GuestReference,
  type PermissionKey,
  type EventPhase,
  type ScopeInput,
  type AuthenticateStaffInput,
  type StaffSession,
  type StaffSessionActor,
} from "./schemas.js";
export {
  OperationalGuestSchema,
  GuestHouseholdSchema,
  GuestDuplicateCandidateSchema,
  IntakeGuestInputSchema,
  AmendGuestInputSchema,
  GuestDirectoryQuerySchema,
  type OperationalGuest,
  type GuestHousehold,
  type GuestDuplicateCandidate,
  type GuestIntakeBatch,
  type QualifiedField,
  type FieldQuality,
} from "./guest-schemas.js";
export {
  GuestAddressingSchema,
  GuestPartySchema,
  GuestPartyMemberSchema,
  GuestRelationshipSchema,
  CompanionEntitlementSchema,
  CompanionNominationSchema,
  ResponsibleAdultLinkSchema,
  EventSeriesSchema,
  EventSeriesMemberSchema,
  AddressingReconciliationItemSchema,
  S04AMigrationReceiptSchema,
  UpdateGuestAddressingInputSchema,
  CreatePartyInputSchema,
  AddPartyMemberInputSchema,
  RemovePartyMemberInputSchema,
  CreateRelationshipInputSchema,
  AdministerRelationshipInputSchema,
  AdministerCompanionEntitlementInputSchema,
  NominateCompanionInputSchema,
  CreateResponsibleAdultLinkInputSchema,
  EndResponsibleAdultLinkInputSchema,
  ReconcileCompanionNamesInputSchema,
  HonorificSchema,
  AgeBandSchema,
  type GuestAddressing,
  type GuestParty,
  type GuestPartyMember,
  type GuestRelationship,
  type CompanionEntitlement,
  type CompanionNomination,
  type ResponsibleAdultLink,
  type CompanionAuthority,
  type CompanionEntitlementStatus,
  type EndResponsibleAdultLinkInput,
  type EventSeries,
  type EventSeriesMember,
  type AgeBand,
  type Honorific,
  type S04AMigrationReceipt,
} from "./addressing-schemas.js";
export {
  communicationsSalutation,
  addressingStatusRequiresConfirm,
  projectGuestAddressing,
  buildGuestAddressingWorkspace,
  type GuestAddressingCapabilities,
  type GuestAddressingProjection,
  type GuestAddressingWorkspace,
  type GuestChildProjection,
  type GuestPartyProjection,
  type GuestPartyMemberProjection,
  type CompanionEntitlementProjection,
} from "./addressing-projections.js";
export {
  validateS04APersistedCollections,
  S04A_UNKNOWN_FIELDS_POLICY,
  S04A_STORE_COLLECTIONS,
} from "./addressing-persistence.js";
export {
  renderGuestSalutation,
  renderFamiliarName,
  composeStoredName,
  childReadinessFor,
  requiresResponsibleAdult,
  unnamedAllowanceHasNoGuest,
  partyIsNotIdentity,
  allowedEntitlementTransitions,
  entitlementTransitionAllowed,
  allowanceExceedsAuthority,
  dateOfBirthForbidden,
  type RenderedSalutation,
} from "./addressing.js";
export {
  operationalDisplayName,
  normalizeEmail,
  normalizePhone,
  findDuplicateMatches,
  fieldValue,
  attentionRequiredFor,
  attentionFieldKeysFor,
  projectGuestAttention,
  ATTENTION_FIELD_KEYS,
} from "./guest-matching.js";
export {
  detectSalutationTitleMismatch,
  titleAppearsInSalutation,
  addressingTitles,
  proposedAddressingTitles,
} from "./addressing-salutation.js";
export {
  assertRetainedSalutationInvariant,
  retainedSalutationInvariant,
  RETAINED_SALUTATION_INVARIANT,
} from "./addressing-invariant.js";
export {
  guestAmendmentAlreadyApplied,
  addressingAlreadyApplied,
} from "./mutation-replay.js";
export { parseCanonicalCsv, CANONICAL_CSV_COLUMNS } from "./guest-intake.js";
export { seededPermissions, seededRoles, permissionsForRole, roleIdForKey } from "./catalog.js";
export { authorize, assignmentIsActive, assignmentCoversScope, canSeeClient, canSeeEvent, singleCoveringRoleKey, type ActorSnapshot, type PolicyDecision } from "./policy.js";
export { allowedNextPhases, assertPhaseTransition } from "./transitions.js";
export { redactValue, stableHash } from "./redaction.js";
export {
  NonProductionIdentityAdapter,
  OidcCompatibleIdentityAdapter,
  assertNamedHuman,
  type IdentityAdapter,
} from "./identity.js";
export {
  issueSession,
  readSession,
  assertSessionConfig,
  hashStaffSessionToken,
  DEFAULT_NON_PRODUCTION_STAFF_SESSION,
  type SessionActor,
  type SessionConfig,
} from "./session.js";
export { FIXTURE_IDS, fixturePersons, isFixtureId, lineageFixtureMark } from "./fixtures.js";
export { emptyMasterEventFile } from "./mef.js";
export { emptySnapshot, normalizeSnapshot, type PlatformStore, type PlatformSnapshot } from "./store.js";
export {
  migrateEosS04A,
  rollbackEosS04A,
  compatibleLegacySnapshot,
  EOS_S04A_MIGRATION_ID,
  type S04AMigrationResult,
  type S04ARollbackResult,
} from "./addressing-migration.js";
export {
  migrateEosS04B,
  rollbackEosS04B,
  applyEosS04BToSnapshot,
  EOS_S04B_MIGRATION_ID,
  EOS_S04B_MIGRATION_CHECKSUM,
  type S04BMigrationResult,
} from "./programme-migration.js";
export {
  applyS04BFixturesIfMissing,
  S04B_FIXTURE_IDS,
} from "./programme-fixtures.js";
export {
  validateS04BPersistedCollections,
  S04B_STORE_COLLECTIONS,
} from "./programme-persistence.js";
export {
  wholeEventAttendanceUnion,
  phaseGuestCount,
  verifyOfflinePackage,
  signOfflinePackageBody,
} from "./programme-operations.js";
export {
  buildEventProgrammeWorkspace,
  buildGuestPhaseProjection,
  programmePermissionAllowed,
  type EventProgrammeWorkspace,
  type ProgrammeCapabilities,
} from "./programme-projections.js";
export {
  migrateEosS04C,
  rollbackEosS04C,
  applyEosS04CToSnapshot,
  migrateEosS04CGuestGrants,
  EOS_S04C_MIGRATION_ID,
  EOS_S04C_MIGRATION_CHECKSUM,
  EOS_S04C_GUEST_GRANT_MIGRATION_ID,
  EOS_S04C_GUEST_GRANT_MIGRATION_CHECKSUM,
  type S04CMigrationResult,
} from "./merchandise-migration.js";
export {
  applyS04CFixturesIfMissing,
  S04C_FIXTURE_IDS,
  S04C_VENDOR_TOKEN,
  S04C_OTHER_VENDOR_TOKEN,
} from "./merchandise-fixtures.js";
export {
  validateS04CPersistedCollections,
  S04C_STORE_COLLECTIONS,
} from "./merchandise-persistence.js";
export {
  migrateEosS04D,
  rollbackEosS04D,
  applyEosS04DToSnapshot,
  EOS_S04D_MIGRATION_ID,
  EOS_S04D_MIGRATION_CHECKSUM,
  type S04DMigrationResult,
} from "./forecast-migration.js";
export {
  applyS04DFixturesIfMissing,
  S04D_FIXTURE_IDS,
  S04D_KNOWN_COUNTS,
} from "./forecast-fixtures.js";
export {
  validateS04DPersistedCollections,
  S04D_STORE_COLLECTIONS,
} from "./forecast-persistence.js";
export {
  assertNoProhibitedForecastFields,
  prohibitedForecastPayload,
  DEFAULT_FORECAST_POLICY_ID,
  DEFAULT_PARAMETER_SET_ID,
  buildForecastPopulation,
  coreTruthFingerprint,
} from "./forecast-operations.js";
export {
  computeForecast,
  classifyAttendanceIntent,
  displayRange,
  currentInputChecksum,
} from "./forecast-model.js";
export {
  buildEventForecastWorkspace,
  buildHostForecastProjection,
  buildForecastOverviewStrip,
  forecastPermissionAllowed,
  type EventForecastWorkspace,
  type ForecastCapabilities,
  type HostForecastProjection,
} from "./forecast-projections.js";
export {
  ForecastPolicySchema,
  ModelParameterSetSchema,
  AttendanceForecastRunSchema,
  ForecastEstimateSchema,
  RunAttendanceForecastInputSchema,
  ProposeForecastOverrideInputSchema,
  DecideForecastOverrideInputSchema,
  ProposeProvisionInputSchema,
  DecideProvisionInputSchema,
  ApproveHostProjectionInputSchema,
  RecordCalibrationObservationInputSchema,
  EvaluateForecastInputSchema,
  CreateEventParameterSetInputSchema,
  type ForecastPolicy,
  type ModelParameterSet,
  type AttendanceForecastRun,
  type ForecastPopulationMember,
  type ForecastEstimate,
  type UncertaintyDriver,
  type ConfidenceAssessment,
  type ForecastOverride,
  type OperationalProvisionRecommendation,
  type CalibrationObservation,
  type ForecastEvaluation,
} from "./forecast-schemas.js";
export {
  assertNoProhibitedMerchandiseFields,
  prohibitedMerchandisePayload,
  assertCapCircumferenceRaw,
} from "./merchandise-operations.js";
export {
  describeMerchandiseAccessState,
  MERCHANDISE_ACCESS_DISPLAY_STATES,
  type MerchandiseAccessDisplayState,
} from "./merchandise-access-state.js";
export {
  buildEventMerchandiseWorkspace,
  buildGuestMerchandiseProjection,
  buildVendorPortalProjection,
  merchandisePermissionAllowed,
  type EventMerchandiseWorkspace,
  type MerchandiseCapabilities,
  type GuestMerchandiseProjection,
  type VendorPortalProjection,
} from "./merchandise-projections.js";
export {
  MerchandiseCollectionSchema,
  MerchandiseItemSchema,
  GuestOfferSchema,
  GuestParticipationSchema,
  CapMeasurementSchema,
  FulfilmentSchema,
  VendorAssignmentSchema,
  CreateMerchandiseCollectionInputSchema,
  CreateHostOfferRuleInputSchema,
  RecordGuestParticipationInputSchema,
  CaptureCapMeasurementInputSchema,
  SubmitVendorUpdateInputSchema,
  type MerchandiseCollection,
  type MerchandiseItem,
  type GuestOffer,
  type GuestParticipation,
  type CapMeasurement,
  type Fulfilment,
  type VendorAssignment,
} from "./merchandise-schemas.js";
export {
  SYNTHETIC_RAILWAY_PROJECT_NAME,
  hostedRuntimeFromEnv,
  resolveAccessAuthority,
  localFixtureAccessAuthority,
  coerceAccessAuthority,
  type AccessAuthority,
  type HostedRuntime,
  type IdentityAdapterKind,
} from "./access-authority.js";
export {
  DEFAULT_NON_PRODUCTION_VENDOR_ACCESS,
  assertVendorAccessConfig,
  readVendorSession,
  resolveVendorAccessFromEnv,
  usesKnownFixtureVendorSecrets,
  vendorSecretFingerprint,
  type VendorAccessConfig,
  type VendorSessionActor,
} from "./merchandise-vendor-access.js";
export {
  DEFAULT_NON_PRODUCTION_MERCHANDISE_GUEST_ACCESS,
  assertMerchandiseGuestAccessConfig,
  readMerchandiseGuestSession,
  type MerchandiseGuestAccessConfig,
  type MerchandiseGuestSessionActor,
} from "./merchandise-guest-access.js";
export {
  ProgrammePhaseSchema,
  PhaseEntitlementSchema,
  ArrivalRouteSchema,
  PerimeterCheckpointSchema,
  CredentialProjectionSchema,
  OperationalVehicleSchema,
  OfflineAccessPackageSchema,
  CreateProgrammePhaseInputSchema,
  AssignPhaseEntitlementInputSchema,
  CreateCheckpointInputSchema,
  CreateArrivalRouteInputSchema,
  CreateVehicleInputSchema,
  PublishOfflinePackageInputSchema,
  ConsumeOfflinePackageInputSchema,
  ResolveCheckpointInputSchema,
  type ProgrammePhase,
  type PhaseEntitlement,
  type ArrivalRoute,
  type PerimeterCheckpoint,
  type CredentialProjection,
  type OperationalVehicle,
  type OfflineAccessPackage,
} from "./programme-schemas.js";
export {
  applyS04AFixtures,
  applyS04AFixturesIfMissing,
  fixtureS04AGuests,
  fixtureS04AHousehold,
  fixtureS03CompanionEntitlement,
  S04A_FIXTURE_IDS,
} from "./addressing-fixtures.js";
export { MemoryPlatformStore } from "./memory-store.js";
export { PLATFORM_POSTGRES_SCHEMA, type PgQueryable, type PgTransactor } from "./postgres-schema.js";
export { PostgresPlatformStore, MemoryPlatformPg } from "./postgres-store.js";
export {
  PLATFORM_MIGRATIONS,
  runPlatformMigrations,
  type MigrationReport,
} from "./migrations.js";
export {
  SYNTHETIC_SEED_ID,
  SYNTHETIC_SEED_VERSION,
  applySyntheticSeedIfNeeded,
  applySyntheticSnapshot,
  readSeedLedger,
} from "./synthetic-seed.js";
export {
  SYNTHETIC_CLEANUP_CONFIRMATION,
  ACCESS_LIFECYCLE_PROBE_VENDOR_ID,
  EVENT_OS_CLEANUP_PROJECT_ID,
  EVENT_OS_CLEANUP_PROJECT_NAME,
  applySyntheticCleanup,
  assertCleanupConfirmation,
  assertCleanupProjectScope,
  classifySyntheticCleanupAttribution,
  previewSyntheticCleanup,
  recordCleanupAudit,
  cleanupAccessLifecycleProbe,
} from "./synthetic-cleanup.js";
export {
  PlatformService,
  type ActorContext,
  type GuestSelfServiceView,
  type IssuedRsvpInvitation,
  type PlatformServiceOptions,
  type RsvpGuestDirectoryRow,
} from "./service.js";
export { loadNonProductionFixtures } from "./bootstrap.js";
export {
  DEFAULT_NON_PRODUCTION_RSVP_ACCESS,
  assertRsvpAccessConfig,
  readGuestSession,
  type RsvpAccessConfig,
  type GuestSessionActor,
} from "./rsvp-access.js";
export {
  RsvpPolicySchema,
  RsvpQuestionnaireSchema,
  RsvpInvitationSchema,
  RsvpResponseSchema,
  GuestRsvpSaveInputSchema,
  type RsvpPolicy,
  type RsvpQuestionnaire,
  type RsvpInvitation,
  type RsvpResponse,
  type RsvpReceipt,
  type RsvpEntitlement,
  type RsvpException,
  type RsvpAssistanceRequest,
  type RsvpAttendanceIntent,
} from "./rsvp-schemas.js";
export { canonicalQuestionnaireSections, guestVisibleName } from "./rsvp-operations.js";
export {
  ALLOWED_TEMPLATE_VARIABLES,
  presentationLabel,
  replyEligibilityPublicMessage,
  signSyntheticPayload,
  projectGuestSafeOccasion,
} from "./communications-operations.js";
export {
  PrepareCommunicationsInputSchema,
  PublishOccasionInputSchema,
  PublishChannelPolicyInputSchema,
  CreateCampaignInputSchema,
  type ChannelPolicy,
  type GuestSafeOccasion,
  type GuestSafeOccasionView,
  type Campaign,
  type MessageTemplate,
  type MessageTemplateVersion,
  type AudienceDefinition,
  type ConversationThread,
  type InboundMessage,
  type FollowUpTask,
  type ContactCorrection,
  type ContactCorrectionReview,
  type ContactCorrectionSourceEvidence,
  type CommsMessage,
  type MsgChannel,
  type MsgPurpose,
} from "./communications-schemas.js";
