export {
  PLATFORM_PACKAGE,
  SHARED_PLATFORM_OWNERSHIP,
  FORBIDDEN_PARALLEL_TRUTH,
  PLATFORM_PERSISTENCE_CONTRACT,
  LOCAL_STORE_PRODUCTION_STATUS,
  PRODUCTION_STORE_STATUS,
  SCHEMA_VERSION,
  DEFAULT_TIMEZONE,
  SESSION_COOKIE,
  RSVP_SESSION_COOKIE,
  STAFF_SESSION_REVOCATION_REASONS,
  STAFF_SESSION_DENIAL_STATUSES,
  type StaffSessionDenialStatus,
  RSVP_ATTENDANCE_INTENTS,
  CORRELATION_HEADER,
  MEF_COMPOSITION_SLOTS,
  EVENT_PHASES,
  PERMISSION_KEYS,
  SYSTEM_ROLE_KEYS,
  CEO_RESERVED_ACTIONS,
  FIELD_QUALITY_STATES,
  GUEST_LIFECYCLE_STATES,
  IDENTITY_RESOLUTION_STATES,
  CANONICAL_INTAKE_MAPPING_VERSION,
  HONORIFICS,
  ADDRESSING_STATUSES,
  AGE_BANDS,
  CHILD_AGE_BANDS,
  PARTY_TYPES,
  RELATIONSHIP_TYPES,
  COMPANION_ENTITLEMENT_STATUSES,
  MSG_CHANNELS,
  MSG_PURPOSES,
  MSG_CAMPAIGN_STATUSES,
  MSG_MESSAGE_STATUSES,
  type StoreProductionStatus,
} from "./constants.js";
export { PlatformError, PLATFORM_ERROR_CODES, publicMessageFor, type PlatformErrorCode } from "./errors.js";
export {
  OrganisationSchema,
  ClientSchema,
  EventRecordSchema,
  PersonSchema,
  MembershipSchema,
  RoleSchema,
  PermissionSchema,
  AssignmentSchema,
  AuditEventSchema,
  MasterEventFileSchema,
  ConsentRecordSchema,
  GuestReferenceSchema,
  ScopeInputSchema,
  CreateClientInputSchema,
  CreateEventInputSchema,
  UpdateEventInputSchema,
  TransitionEventInputSchema,
  GrantAssignmentInputSchema,
  SignInInputSchema,
  AuthenticateStaffInputSchema,
  StaffSessionSchema,
  StaffSessionActorSchema,
  type Organisation,
  type Client,
  type EventRecord,
  type Person,
  type Membership,
  type Role,
  type Permission,
  type Assignment,
  type AuditEvent,
  type MasterEventFile,
  type ConsentRecord,
  type GuestReference,
  type PermissionKey,
  type EventPhase,
  type ScopeInput,
  type AuthenticateStaffInput,
  type StaffSession,
  type StaffSessionActor,
} from "./schemas.js";
export {
  OperationalGuestSchema,
  GuestHouseholdSchema,
  GuestDuplicateCandidateSchema,
  IntakeGuestInputSchema,
  AmendGuestInputSchema,
  GuestDirectoryQuerySchema,
  type OperationalGuest,
  type GuestHousehold,
  type GuestDuplicateCandidate,
  type GuestIntakeBatch,
  type QualifiedField,
  type FieldQuality,
} from "./guest-schemas.js";
export {
  GuestAddressingSchema,
  GuestPartySchema,
  GuestPartyMemberSchema,
  GuestRelationshipSchema,
  CompanionEntitlementSchema,
  CompanionNominationSchema,
  ResponsibleAdultLinkSchema,
  EventSeriesSchema,
  EventSeriesMemberSchema,
  AddressingReconciliationItemSchema,
  S04AMigrationReceiptSchema,
  UpdateGuestAddressingInputSchema,
  CreatePartyInputSchema,
  AddPartyMemberInputSchema,
  RemovePartyMemberInputSchema,
  CreateRelationshipInputSchema,
  AdministerCompanionEntitlementInputSchema,
  NominateCompanionInputSchema,
  CreateResponsibleAdultLinkInputSchema,
  ReconcileCompanionNamesInputSchema,
  HonorificSchema,
  AgeBandSchema,
  type GuestAddressing,
  type GuestParty,
  type GuestPartyMember,
  type GuestRelationship,
  type CompanionEntitlement,
  type CompanionNomination,
  type ResponsibleAdultLink,
  type EventSeries,
  type EventSeriesMember,
  type AgeBand,
  type Honorific,
  type S04AMigrationReceipt,
} from "./addressing-schemas.js";
export {
  communicationsSalutation,
  projectGuestAddressing,
  buildGuestAddressingWorkspace,
  type GuestAddressingCapabilities,
  type GuestAddressingProjection,
  type GuestAddressingWorkspace,
  type GuestChildProjection,
  type CompanionEntitlementProjection,
} from "./addressing-projections.js";
export {
  validateS04APersistedCollections,
  S04A_UNKNOWN_FIELDS_POLICY,
  S04A_STORE_COLLECTIONS,
} from "./addressing-persistence.js";
export {
  renderGuestSalutation,
  renderFamiliarName,
  composeStoredName,
  childReadinessFor,
  requiresResponsibleAdult,
  unnamedAllowanceHasNoGuest,
  partyIsNotIdentity,
  entitlementTransitionAllowed,
  allowanceExceedsAuthority,
  dateOfBirthForbidden,
  type RenderedSalutation,
} from "./addressing.js";
export { operationalDisplayName, normalizeEmail, normalizePhone, findDuplicateMatches, fieldValue } from "./guest-matching.js";
export { parseCanonicalCsv, CANONICAL_CSV_COLUMNS } from "./guest-intake.js";
export { seededPermissions, seededRoles, permissionsForRole, roleIdForKey } from "./catalog.js";
export { authorize, assignmentIsActive, assignmentCoversScope, canSeeClient, canSeeEvent, singleCoveringRoleKey, type ActorSnapshot, type PolicyDecision } from "./policy.js";
export { allowedNextPhases, assertPhaseTransition } from "./transitions.js";
export { redactValue, stableHash } from "./redaction.js";
export {
  NonProductionIdentityAdapter,
  OidcCompatibleIdentityAdapter,
  assertNamedHuman,
  type IdentityAdapter,
} from "./identity.js";
export {
  issueSession,
  readSession,
  assertSessionConfig,
  hashStaffSessionToken,
  DEFAULT_NON_PRODUCTION_STAFF_SESSION,
  type SessionActor,
  type SessionConfig,
} from "./session.js";
export { FIXTURE_IDS, fixturePersons, isFixtureId, lineageFixtureMark } from "./fixtures.js";
export { emptyMasterEventFile } from "./mef.js";
export { emptySnapshot, normalizeSnapshot, type PlatformStore, type PlatformSnapshot } from "./store.js";
export {
  migrateEosS04A,
  rollbackEosS04A,
  compatibleLegacySnapshot,
  EOS_S04A_MIGRATION_ID,
  type S04AMigrationResult,
  type S04ARollbackResult,
} from "./addressing-migration.js";
export {
  applyS04AFixtures,
  applyS04AFixturesIfMissing,
  fixtureS04AGuests,
  fixtureS04AHousehold,
  fixtureS03CompanionEntitlement,
  S04A_FIXTURE_IDS,
} from "./addressing-fixtures.js";
export { MemoryPlatformStore } from "./memory-store.js";
export { PLATFORM_POSTGRES_SCHEMA, type PgQueryable, type PgTransactor } from "./postgres-schema.js";
export { PostgresPlatformStore, MemoryPlatformPg } from "./postgres-store.js";
export {
  PLATFORM_MIGRATIONS,
  runPlatformMigrations,
  type MigrationReport,
} from "./migrations.js";
export {
  SYNTHETIC_SEED_ID,
  SYNTHETIC_SEED_VERSION,
  applySyntheticSeedIfNeeded,
  applySyntheticSnapshot,
  readSeedLedger,
} from "./synthetic-seed.js";
export {
  SYNTHETIC_CLEANUP_CONFIRMATION,
  EVENT_OS_CLEANUP_PROJECT_ID,
  EVENT_OS_CLEANUP_PROJECT_NAME,
  applySyntheticCleanup,
  assertCleanupConfirmation,
  assertCleanupProjectScope,
  classifySyntheticCleanupAttribution,
  previewSyntheticCleanup,
  recordCleanupAudit,
} from "./synthetic-cleanup.js";
export {
  PlatformService,
  type ActorContext,
  type GuestSelfServiceView,
  type IssuedRsvpInvitation,
  type PlatformServiceOptions,
  type RsvpGuestDirectoryRow,
} from "./service.js";
export { loadNonProductionFixtures } from "./bootstrap.js";
export {
  DEFAULT_NON_PRODUCTION_RSVP_ACCESS,
  assertRsvpAccessConfig,
  readGuestSession,
  type RsvpAccessConfig,
  type GuestSessionActor,
} from "./rsvp-access.js";
export {
  RsvpPolicySchema,
  RsvpQuestionnaireSchema,
  RsvpInvitationSchema,
  RsvpResponseSchema,
  GuestRsvpSaveInputSchema,
  type RsvpPolicy,
  type RsvpQuestionnaire,
  type RsvpInvitation,
  type RsvpResponse,
  type RsvpReceipt,
  type RsvpEntitlement,
  type RsvpException,
  type RsvpAssistanceRequest,
  type RsvpAttendanceIntent,
} from "./rsvp-schemas.js";
export { canonicalQuestionnaireSections, guestVisibleName } from "./rsvp-operations.js";
export {
  ALLOWED_TEMPLATE_VARIABLES,
  presentationLabel,
  replyEligibilityPublicMessage,
  signSyntheticPayload,
  projectGuestSafeOccasion,
} from "./communications-operations.js";
export {
  PrepareCommunicationsInputSchema,
  PublishOccasionInputSchema,
  PublishChannelPolicyInputSchema,
  CreateCampaignInputSchema,
  type ChannelPolicy,
  type GuestSafeOccasion,
  type GuestSafeOccasionView,
  type Campaign,
  type MessageTemplate,
  type MessageTemplateVersion,
  type AudienceDefinition,
  type ConversationThread,
  type InboundMessage,
  type FollowUpTask,
  type ContactCorrection,
  type ContactCorrectionReview,
  type ContactCorrectionSourceEvidence,
  type CommsMessage,
  type MsgChannel,
  type MsgPurpose,
} from "./communications-schemas.js";
