import { SCHEMA_VERSION } from "./constants.js";
import { S04A_FIXTURE_IDS } from "./addressing-fixtures.js";
import { FIXTURE_IDS } from "./fixtures.js";
import { accentInsensitiveSearchKey } from "./language-unicode.js";
import type { PlatformSnapshot } from "./store.js";

export const S04F_FIXTURE_IDS = {
  profileOlufemi: "00000000-0000-4000-8000-000000000130",
  historyOlufemi: "00000000-0000-4000-8000-000000000131",
  culturalGreeting: "00000000-0000-4000-8000-000000000132",
  culturalReview: "00000000-0000-4000-8000-000000000133",
  workInvitation: "00000000-0000-4000-8000-000000000134",
  editionEnGb: "00000000-0000-4000-8000-000000000135",
  editionYo: "00000000-0000-4000-8000-000000000136",
  editionFr: "00000000-0000-4000-8000-000000000137",
  editionDe: "00000000-0000-4000-8000-000000000138",
  editionZh: "00000000-0000-4000-8000-000000000139",
  editionIg: "00000000-0000-4000-8000-00000000013a",
  blockEnPrimary: "00000000-0000-4000-8000-00000000013b",
  blockYoGreeting: "00000000-0000-4000-8000-00000000013c",
  blockFrPrimary: "00000000-0000-4000-8000-00000000013d",
  blockDePrimary: "00000000-0000-4000-8000-00000000013e",
  blockDeTarget: "00000000-0000-4000-8000-00000000013f",
  blockZhPrimary: "00000000-0000-4000-8000-000000000140",
  blockIgDraft: "00000000-0000-4000-8000-000000000141",
  linkYo: "00000000-0000-4000-8000-000000000142",
  linkFr: "00000000-0000-4000-8000-000000000143",
  linkDe: "00000000-0000-4000-8000-000000000144",
  linkZh: "00000000-0000-4000-8000-000000000145",
  termAlakija: "00000000-0000-4000-8000-000000000146",
  reviewFr: "00000000-0000-4000-8000-000000000147",
  ruleInvitation: "00000000-0000-4000-8000-000000000148",
  assemblyOlufemi: "00000000-0000-4000-8000-000000000149",
  coverageInvitation: "00000000-0000-4000-8000-00000000014a",
  workHost: "00000000-0000-4000-8000-00000000014b",
  editionHostEn: "00000000-0000-4000-8000-00000000014c",
  editionHostFr: "00000000-0000-4000-8000-00000000014d",
  blockHostEn: "00000000-0000-4000-8000-00000000014e",
  blockHostFr: "00000000-0000-4000-8000-00000000014f",
  linkHostFr: "00000000-0000-4000-8000-000000000150",
  ruleHost: "00000000-0000-4000-8000-000000000151",
} as const;

const AT = "2026-09-07T20:00:00.000Z";

function stamp<T extends object>(value: T) {
  return {
    ...value,
    nonProductionFixture: true as const,
    schemaVersion: SCHEMA_VERSION,
    version: 1,
    createdAt: AT,
    updatedAt: AT,
  };
}

function scoped() {
  return {
    organisationId: FIXTURE_IDS.orgMaison,
    clientId: FIXTURE_IDS.clientAlpha,
    eventId: FIXTURE_IDS.eventAlphaOne,
  };
}

const INVITE_EN =
  "Dear {{guestName}}, Maison Doclar welcomes you. Ẹ̀kú àbọ̀ is reserved as a governed greeting. Willkommensveranstaltungseinladung remains untranslated. 欢迎光临 is a synthetic Chinese close.";

export function applyS04FFixturesIfMissing(input: PlatformSnapshot): PlatformSnapshot {
  if (input.contentWorks.some((item) => item.id === S04F_FIXTURE_IDS.workInvitation)) return input;
  if (!input.operationalGuests.some((item) => item.id === S04A_FIXTURE_IDS.guestOlufemi)) return input;
  const snap = structuredClone(input);
  snap.languageProfiles.push(
    stamp({
      id: S04F_FIXTURE_IDS.profileOlufemi,
      ...scoped(),
      guestId: S04A_FIXTURE_IDS.guestOlufemi,
      preferredLanguageTag: "yo",
      additionalUnderstoodLanguageTags: ["en-GB"],
      englishAcceptable: true,
      translationRequired: true,
      preferredPresentationMode: "PRIMARY_PLUS_SUMMARY",
      source: "GUEST_SUPPLIED",
      unknown: false,
      confirmedAt: AT,
      confirmedByPersonId: FIXTURE_IDS.personPlanner,
      recordedByPersonId: FIXTURE_IDS.personPlanner,
    }),
  );
  snap.languagePreferenceHistories.push(
    stamp({
      id: S04F_FIXTURE_IDS.historyOlufemi,
      ...scoped(),
      guestId: S04A_FIXTURE_IDS.guestOlufemi,
      profileId: S04F_FIXTURE_IDS.profileOlufemi,
      nextLanguageTag: "yo",
      previousUnknown: true,
      nextUnknown: false,
      source: "GUEST_SUPPLIED",
      actorPersonId: FIXTURE_IDS.personPlanner,
      reason: "Explicit guest-supplied Yorùbá preference. Synthetic fixture.",
    }),
  );
  snap.culturalSourceTexts.push(
    stamp({
      id: S04F_FIXTURE_IDS.culturalGreeting,
      ...scoped(),
      exactText: "Ẹ kú àbọ̀",
      languageTag: "yo",
      purpose: "Arrival greeting",
      culturalMeaning: "A respectful welcome. Synthetic fixture — not culturally validated.",
      usageNote: "Use only inside an approved edition. Do not treat this fixture as specialist-validated Yorùbá.",
      provenance: "Synthetic EOS-S04F fixture. Unvalidated.",
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      specialistValidated: false,
      status: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
      searchKey: accentInsensitiveSearchKey("Ẹ kú àbọ̀"),
      approvedAt: AT,
      approvedByPersonId: FIXTURE_IDS.personDirector,
    }),
  );
  snap.reviewAssignments.push(
    stamp({
      id: S04F_FIXTURE_IDS.culturalReview,
      ...scoped(),
      kind: "CULTURAL",
      subjectType: "CULTURAL_SOURCE_TEXT",
      subjectId: S04F_FIXTURE_IDS.culturalGreeting,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      proposerPersonId: FIXTURE_IDS.personPlanner,
      decision: "APPROVED",
      decidedAt: AT,
      notes: "Workflow approval only. Not specialist cultural validation.",
    }),
  );
  snap.contentWorks.push(
    stamp({
      id: S04F_FIXTURE_IDS.workInvitation,
      ...scoped(),
      title: "Alpha One arrival greeting",
      purpose: "GUEST_MESSAGE",
      englishConvention: "en-GB",
      primaryLanguageTag: "en-GB",
      primaryEditionId: S04F_FIXTURE_IDS.editionEnGb,
      currentEditionId: S04F_FIXTURE_IDS.editionEnGb,
      hostFacing: false,
      ownerPersonId: FIXTURE_IDS.personPlanner,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.workHost,
      ...scoped(),
      title: "Host edition — welcome words",
      purpose: "ATELIER_NARRATIVE",
      englishConvention: "en-GB",
      primaryLanguageTag: "en-GB",
      primaryEditionId: S04F_FIXTURE_IDS.editionHostEn,
      currentEditionId: S04F_FIXTURE_IDS.editionHostFr,
      hostFacing: true,
      ownerPersonId: FIXTURE_IDS.personPlanner,
    }),
  );
  snap.contentEditions.push(
    stamp({
      id: S04F_FIXTURE_IDS.editionEnGb,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "en-GB",
      kind: "PRIMARY",
      status: "APPROVED",
      authorPersonId: FIXTURE_IDS.personPlanner,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionYo,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "yo",
      kind: "PARTIAL",
      status: "APPROVED",
      sourceEditionId: S04F_FIXTURE_IDS.editionEnGb,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "PARTIAL",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionFr,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "fr",
      kind: "COMPLETE",
      status: "APPROVED",
      sourceEditionId: S04F_FIXTURE_IDS.editionEnGb,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionDe,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "de-DE",
      kind: "BILINGUAL",
      status: "APPROVED",
      sourceEditionId: S04F_FIXTURE_IDS.editionEnGb,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "PARTIAL",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionZh,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "zh-Hans",
      kind: "COMPLETE",
      status: "APPROVED",
      sourceEditionId: S04F_FIXTURE_IDS.editionEnGb,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionIg,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      languageTag: "ig",
      kind: "PARTIAL",
      status: "DRAFT",
      sourceEditionId: S04F_FIXTURE_IDS.editionEnGb,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewRequired: false,
      coverageStatus: "PARTIAL",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionHostEn,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workHost,
      languageTag: "en-GB",
      kind: "PRIMARY",
      status: "APPROVED",
      authorPersonId: FIXTURE_IDS.personPlanner,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.editionHostFr,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workHost,
      languageTag: "fr",
      kind: "COMPLETE",
      status: "APPROVED",
      sourceEditionId: S04F_FIXTURE_IDS.editionHostEn,
      authorPersonId: FIXTURE_IDS.personPlanner,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      reviewRequired: false,
      coverageStatus: "APPROVED",
      culturallyAuthoritative: false,
      syntheticUnvalidated: true,
    }),
  );
  snap.contentBlocks.push(
    stamp({
      id: S04F_FIXTURE_IDS.blockEnPrimary,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionEnGb,
      languageTag: "en-GB",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: INVITE_EN,
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockYoGreeting,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionYo,
      languageTag: "yo",
      purpose: "GREETING",
      sortOrder: 0,
      exactText: "Ẹ kú àbọ̀, {{guestName}}.",
      culturalSourceTextId: S04F_FIXTURE_IDS.culturalGreeting,
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockFrPrimary,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionFr,
      languageTag: "fr",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: "Cher {{guestName}}, Maison Doclar vous souhaite la bienvenue. Ceci est une édition française synthétique et non validée.",
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockDePrimary,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionDe,
      languageTag: "en-GB",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: INVITE_EN,
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockDeTarget,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionDe,
      languageTag: "de-DE",
      purpose: "SUMMARY",
      sortOrder: 1,
      exactText: "Liebe {{guestName}}, dies ist eine synthetische Willkommensveranstaltungseinladung.",
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockZhPrimary,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionZh,
      languageTag: "zh-Hans",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: "亲爱的{{guestName}}，欢迎光临。此为未经验证的综合中文版本。",
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockIgDraft,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      editionId: S04F_FIXTURE_IDS.editionIg,
      languageTag: "ig",
      purpose: "GREETING",
      sortOrder: 0,
      exactText: "Nnọọ {{guestName}}.",
      placeholderNames: ["guestName"],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockHostEn,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workHost,
      editionId: S04F_FIXTURE_IDS.editionHostEn,
      languageTag: "en-GB",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: "A quiet welcome for the host edition. Synthetic and unvalidated.",
      placeholderNames: [],
    }),
    stamp({
      id: S04F_FIXTURE_IDS.blockHostFr,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workHost,
      editionId: S04F_FIXTURE_IDS.editionHostFr,
      languageTag: "fr",
      purpose: "PRIMARY",
      sortOrder: 0,
      exactText: "Un accueil calme pour l’édition hôte. Texte synthétique, non validé.",
      placeholderNames: [],
    }),
  );
  const link = (
    id: string,
    targetEditionId: string,
    targetBlockId: string,
    targetLanguageTag: "yo" | "fr" | "de-DE" | "zh-Hans",
    sourceBlockId: string = S04F_FIXTURE_IDS.blockEnPrimary,
    sourceEditionId: string = S04F_FIXTURE_IDS.editionEnGb,
  ) =>
    stamp({
      id,
      ...scoped(),
      workId: targetEditionId === S04F_FIXTURE_IDS.editionHostFr ? S04F_FIXTURE_IDS.workHost : S04F_FIXTURE_IDS.workInvitation,
      sourceEditionId,
      sourceBlockId,
      sourceLanguageTag: "en-GB" as const,
      targetEditionId,
      targetBlockId,
      targetLanguageTag,
      translatorPersonId: FIXTURE_IDS.personPlanner,
      sourceType: "SYNTHETIC_FIXTURE" as const,
      reviewStatus: "APPROVED" as const,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      approvedByPersonId: FIXTURE_IDS.personDirector,
      approvedAt: AT,
      stale: false,
    });
  snap.translationLinks.push(
    link(S04F_FIXTURE_IDS.linkYo, S04F_FIXTURE_IDS.editionYo, S04F_FIXTURE_IDS.blockYoGreeting, "yo"),
    link(S04F_FIXTURE_IDS.linkFr, S04F_FIXTURE_IDS.editionFr, S04F_FIXTURE_IDS.blockFrPrimary, "fr"),
    link(S04F_FIXTURE_IDS.linkDe, S04F_FIXTURE_IDS.editionDe, S04F_FIXTURE_IDS.blockDeTarget, "de-DE"),
    link(S04F_FIXTURE_IDS.linkZh, S04F_FIXTURE_IDS.editionZh, S04F_FIXTURE_IDS.blockZhPrimary, "zh-Hans"),
    link(
      S04F_FIXTURE_IDS.linkHostFr,
      S04F_FIXTURE_IDS.editionHostFr,
      S04F_FIXTURE_IDS.blockHostFr,
      "fr",
      S04F_FIXTURE_IDS.blockHostEn,
      S04F_FIXTURE_IDS.editionHostEn,
    ),
  );
  snap.terminologyEntries.push(
    stamp({
      id: S04F_FIXTURE_IDS.termAlakija,
      ...scoped(),
      term: "Olufemi Alakija",
      languageTag: "yo",
      approvedDisplayForm: "Olúfẹ́mi Alákíjà",
      searchKey: accentInsensitiveSearchKey("Olufemi Alakija"),
      meaning: "Approved tonal-marked display form. Synthetic fixture.",
      policy: "RETAIN",
      context: "Canonical name; never auto-translated.",
      ownerPersonId: FIXTURE_IDS.personPlanner,
    }),
  );
  snap.reviewAssignments.push(
    stamp({
      id: S04F_FIXTURE_IDS.reviewFr,
      ...scoped(),
      kind: "LINGUISTIC",
      subjectType: "CONTENT_EDITION",
      subjectId: S04F_FIXTURE_IDS.editionFr,
      reviewerPersonId: FIXTURE_IDS.personDirector,
      proposerPersonId: FIXTURE_IDS.personPlanner,
      decision: "APPROVED",
      decidedAt: AT,
      notes: "Synthetic French edition. Not culturally authoritative.",
    }),
  );
  snap.recipientEditionRules.push(
    stamp({
      id: S04F_FIXTURE_IDS.ruleInvitation,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      fallbackLanguageTag: "en-GB",
      allowPartialFallback: true,
      explanation: "Terminal fallback is en-GB. Explicit preference is never overwritten.",
      ownerPersonId: FIXTURE_IDS.personPlanner,
    }),
    stamp({
      id: S04F_FIXTURE_IDS.ruleHost,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workHost,
      fallbackLanguageTag: "en-GB",
      allowPartialFallback: false,
      explanation: "Host edition uses the approved French current edition.",
      ownerPersonId: FIXTURE_IDS.personPlanner,
    }),
  );
  snap.recipientAssemblies.push(
    stamp({
      id: S04F_FIXTURE_IDS.assemblyOlufemi,
      ...scoped(),
      guestId: S04A_FIXTURE_IDS.guestOlufemi,
      workId: S04F_FIXTURE_IDS.workInvitation,
      contentPurpose: "GUEST_MESSAGE",
      requestedLanguageTag: "yo",
      selectedLanguageTag: "yo",
      editionId: S04F_FIXTURE_IDS.editionYo,
      units: [
        {
          blockId: S04F_FIXTURE_IDS.blockEnPrimary,
          requestedLanguageTag: "yo",
          selectedLanguageTag: "yo",
          selectedEditionId: S04F_FIXTURE_IDS.editionYo,
          selectedBlockId: S04F_FIXTURE_IDS.blockYoGreeting,
          fallbackUsed: false,
          approvalStatus: "APPROVED",
          renderedText: "Ẹ kú àbọ̀, Olúfẹ́mi Alákíjà.",
        },
      ],
      addressingDisplayName: "Olúfẹ́mi Alákíjà",
      assemblyHash: "s04f-synthetic-olufemi-yo",
      readyForCommsReview: true,
      dispatched: false,
      providerInvoked: false,
      status: "READY_FOR_COMMS_REVIEW",
      assembledByPersonId: FIXTURE_IDS.personPlanner,
      placeholdersValid: true,
    }),
  );
  snap.languageCoverageSnapshots.push(
    stamp({
      id: S04F_FIXTURE_IDS.coverageInvitation,
      ...scoped(),
      workId: S04F_FIXTURE_IDS.workInvitation,
      coverageStatus: "PARTIAL",
      unresolvedPreferenceCount: 4,
      englishOnlyCount: 0,
      mixedFallbackCount: 2,
      blockedCount: 0,
      targetCounts: { "en-GB": 1, "en-US": 0, yo: 1, ig: 0, ha: 0, fr: 1, "de-DE": 1, "zh-Hans": 1 },
      explanation: "Partial Yorùbá and bilingual German remain clearly partial. French and Chinese complete editions are approved synthetic fixtures.",
    }),
  );
  return snap;
}
