export const ACCENT_THEMES = {
  champagne: {
    accent: "#D4AF37",
    hoverDark: "#E5C156",
    hoverLight: "#8F7520",
    active: "#B8952B",
    foreground: "#1A1408",
    accessibleLight: "#6B5510",
  },
  emerald: {
    accent: "#2E8B65",
    hoverDark: "#3FA37A",
    hoverLight: "#1F6B4A",
    active: "#1B5C40",
    foreground: "#07140F",
    accessibleLight: "#1F6B4A",
  },
  navy: {
    accent: "#3D5A80",
    hoverDark: "#4E6E99",
    hoverLight: "#1B2A4A",
    active: "#16304F",
    foreground: "#F4F7FB",
    accessibleLight: "#1B2A4A",
  },
  copper: {
    accent: "#B87333",
    hoverDark: "#C98444",
    hoverLight: "#8A4F1F",
    active: "#8F5424",
    foreground: "#1A1008",
    accessibleLight: "#8A4F1F",
  },
} as const;

export const ACTIVE_ACCENT_THEME = "champagne" as const;

const champagne = ACCENT_THEMES.champagne;

export const THEME_PALETTES = {
  dark: {
    bgPage: "#0A0A0A",
    surfacePrimary: "#141414",
    surfaceRaised: "#1A1A1A",
    surfaceElevated: "#242424",
    surfaceSubtle: "#1A1A1A",
    textPrimary: "#E8E8E8",
    textSecondary: "#A8A8A8",
    textTertiary: "#666666",
    borderSubtle: "rgba(255,255,255,0.08)",
    borderStrong: "rgba(255,255,255,0.18)",
    accent: champagne.accent,
    accentHover: champagne.hoverDark,
    accentActive: champagne.active,
    accentForeground: champagne.foreground,
    accentAccessible: champagne.accent,
    focusRing: champagne.accent,
    success: "#7CB88A",
    warning: "#D4B86A",
    error: "#D98980",
    information: "#8AA7C2",
    overlay: "rgba(10,10,10,0.72)",
  },
  light: {
    bgPage: "#F9F8F6",
    surfacePrimary: "#FFFFFF",
    surfaceRaised: "#FFFFFF",
    surfaceElevated: "#F5F4F2",
    surfaceSubtle: "#F5F4F2",
    textPrimary: "#1A1A1A",
    textSecondary: "#5A5A5A",
    textTertiary: "#B0B0B0",
    borderSubtle: "rgba(0,0,0,0.08)",
    borderStrong: "rgba(0,0,0,0.18)",
    accent: champagne.accent,
    accentHover: "#C4A02A",
    accentActive: champagne.active,
    accentForeground: champagne.foreground,
    accentAccessible: champagne.accessibleLight,
    focusRing: "#6B5510",
    success: "#2F5D3A",
    warning: "#8A6A1F",
    error: "#8A3A32",
    information: "#2C4A6E",
    overlay: "rgba(26,26,26,0.48)",
  },
} as const;

export const DESIGN_TOKENS = {
  color: {
    bgPage: THEME_PALETTES.dark.bgPage,
    surfacePrimary: THEME_PALETTES.dark.surfacePrimary,
    surfaceRaised: THEME_PALETTES.dark.surfaceRaised,
    surfaceElevated: THEME_PALETTES.dark.surfaceElevated,
    surfaceSubtle: THEME_PALETTES.dark.surfaceSubtle,
    textPrimary: THEME_PALETTES.dark.textPrimary,
    textSecondary: THEME_PALETTES.dark.textSecondary,
    textTertiary: THEME_PALETTES.dark.textTertiary,
    borderSubtle: THEME_PALETTES.dark.borderSubtle,
    borderStrong: THEME_PALETTES.dark.borderStrong,
    accent: champagne.accent,
    accentHover: champagne.hoverDark,
    accentActive: champagne.active,
    accentForeground: champagne.foreground,
    focusRing: champagne.accent,
    success: THEME_PALETTES.dark.success,
    warning: THEME_PALETTES.dark.warning,
    error: THEME_PALETTES.dark.error,
    information: THEME_PALETTES.dark.information,
    overlay: THEME_PALETTES.dark.overlay,
    ink: THEME_PALETTES.dark.textPrimary,
    muted: THEME_PALETTES.dark.textSecondary,
    paper: THEME_PALETTES.dark.bgPage,
    raised: THEME_PALETTES.dark.surfacePrimary,
    line: THEME_PALETTES.dark.borderSubtle,
    brass: champagne.accent,
    focus: champagne.accent,
    danger: THEME_PALETTES.dark.error,
    warn: THEME_PALETTES.dark.warning,
    ok: THEME_PALETTES.dark.success,
  },
  space: [4, 8, 12, 16, 20, 24, 32, 48] as const,
  radius: { sm: 6, md: 8, lg: 10 },
  font: {
    family: '"Inter", "Helvetica Neue", Helvetica, Arial, sans-serif',
    display: 'var(--font-display), "Iowan Old Style", "Palatino Linotype", Palatino, "Times New Roman", serif',
    xs: "0.75rem",
    sm: "0.875rem",
    body: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    small: "0.875rem",
  },
  motion: {
    duration: "220ms",
    durationSlow: "320ms",
    ease: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  contentWidth: 1200,
  touch: 44,
} as const;

export const STATUS_WORDS = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  ARCHIVED: "Archived",
  DISCOVER: "Discover",
  DESIGN: "Design",
  PREPARE: "Prepare",
  READY: "Ready",
  LIVE: "Live",
  CLOSE: "Close",
  LEARN: "Learn",
} as const;
