import { ACA_S04A_COURSE_ID, AUTHORITY_DISCLAIMER } from "./constants.js";
import { AcademyCourseSchema, type AcademyCourse, type AcademyLearningPath } from "./schemas.js";

const ALL: AcademyLearningPath[] = [
  "CEO_OVERSIGHT",
  "EVENT_DIRECTOR",
  "PLANNER",
  "OPERATIONAL_AWARENESS",
  "AUDITOR_READ_ONLY",
];
const OPERATORS: AcademyLearningPath[] = ["EVENT_DIRECTOR", "PLANNER", "OPERATIONAL_AWARENESS"];
const GOVERNORS: AcademyLearningPath[] = ["CEO_OVERSIGHT", "EVENT_DIRECTOR", "AUDITOR_READ_ONLY"];

export const acaS04ACourse: AcademyCourse = AcademyCourseSchema.parse({
  id: ACA_S04A_COURSE_ID,
  title: "Guest addressing, relationships and party entitlements",
  lede: "Learn how Event OS records people, parties and companion allowances without inventing titles, households or extra guests. Passing this course is training evidence only.",
  objectives: [
    "Capture a titled adult and a blank-title adult without inference.",
    "Render confirmed formal and familiar forms consistently, keeping Yorùbá diacritics.",
    "Record a child with an age band and a responsible adult — never a full date of birth.",
    "Treat household and entourage parties as containers of independent guest identities.",
    "Administer unnamed plus-one allowance, accept, decline, expire, revoke and materialise exactly once.",
    "Correct title or relationship only through a governed, versioned amend.",
    "Keep S03 as invitation, RSVP and quantity authority; never treat party membership as those truths.",
    "Explain why course completion is not operational authorisation.",
  ],
  modules: [
    {
      id: "objectives",
      title: "What this course is — and is not",
      objective: "Separate training evidence from Event OS authority.",
      instruction:
        "ACA-S04A teaches the Event OS guest, party and entitlement rules already implemented in the platform. Enrolment follows your existing assignment role. A pass (80–89%) or distinction (90%+) is recorded against your person. It does not open permissions, assign a role, sign a protected gate or authorise production. An event briefing may still be required before live work.",
      practice: "State one thing a distinction gives you, and one thing it never gives you.",
      feedback: "A distinction is training evidence. Operational permission still comes only from an active Event OS assignment.",
    },
    {
      id: "names",
      title: "Structured names and optional titles",
      objective: "Create titled and blank-title adults and render formal/familiar forms without guessing.",
      instruction:
        "Given name, optional middle names, family name, optional honorific, professional title, traditional title, post-nominals, preferred display name and preferred formal salutation are structured fields. Leave honorific blank when no title was supplied. Do not infer Mr, Mrs, Dr or a chieftaincy from a Yorùbá or Nigerian name. Formal form is used only when confirmation is authorised and a preferred formal salutation exists. Familiar form uses preferred display or given name. Diacritics such as Ọmọ́tọ́lá and Ẹ̀bùnolúwa must survive persist and reload. Names wrap by word, never character by character.",
      practice: "Intake Professor Ọmọ́tọ́lá Ọlábọ́dé and Adéṣínà with a blank honorific. Confirm only if your role may confirm.",
      feedback: "The titled record keeps the supplied Professor title. Adéṣínà stays untitled. The system must not invent a courtesy title.",
    },
    {
      id: "parties",
      title: "Parties, households and independent identities",
      objective: "Create household and entourage containers without collapsing people.",
      instruction:
        "A party is a relationship container with its own identifier. It is never a guest. Household and INVITATION_PARTY (entourage) types group independently identified members. Do not infer a principal, spouse or household from shared names. Each member keeps a guest ID and can be opened on their own dossier. Removing a member does not delete the guest. Party membership is not invitation truth and not RSVP truth — those remain EOS-S03.",
      practice: "Create an entourage labelled for Ọmọ́tọ́lá and add Ẹ̀bùnolúwa as a member without making either the party.",
      feedback: "You should see one party ID and two guest IDs. The party label is not a person.",
    },
    {
      id: "children",
      title: "Children and responsible adults",
      objective: "Record a child with an age band and an active responsible-adult link, without collecting date of birth.",
      instruction:
        "Use age band only. Full date of birth is forbidden. A child band cannot be READY FOR EVENT without a valid active responsible-adult link. Ending the link returns the child to blocked. Do not expose raw child or protocol records beyond the minimum projection. Direct communication controls stay off the child dossier.",
      practice: "Intake Kọ́ládé as CHILD, confirm the blocked state, then link Ẹ̀bùnolúwa. Do not look for a birth-date field.",
      feedback: "Readiness follows the link. If the adult is removed, the child is blocked again. No date of birth was stored.",
    },
    {
      id: "entitlements",
      title: "Companion entitlement lifecycle",
      objective: "Issue, accept, decline, expire, revoke and materialise a plus-one without fabricating people.",
      instruction:
        "S03 owns invitation, RSVP and allowance quantity. S04A administers the companion entitlement that sits on that authority. An unnamed allowance is a number, not a guest, and must not inflate people counts. Available → nominated/confirmed (accept) → declined, expired or revoked are governed transitions. Materialising a named companion creates or resolves exactly one guest. Retry with the same key must not create a second guest. Planner may administer the routine lifecycle but cannot expand the S03 quantity or review exceptions. CEO and Event Director remain governed. Auditor is read-only.",
      practice: "On an unnamed allowance, decline, restore, expire, revoke as permitted, then materialise Fọláṣadé Adékúnlé once and retry.",
      feedback: "Unnamed never became a person. Exactly one companion guest appeared. A second materialise did not duplicate them.",
    },
    {
      id: "corrections",
      title: "Governed title and relationship correction",
      objective: "Amend only through versioned, permissioned, audited writes.",
      instruction:
        "A title change is a structured addressing amend with expectedVersion, source and reason. Confirmation is a separate permission. A relationship correction is a declared relationship or responsible-adult change — never an inferred spouse or household. Optimistic conflict means reload; retry without reload is unsafe. Every success writes append-only audit.",
      practice: "Correct a supplied honorific, then change a responsible-adult link. Watch the audit line.",
      feedback: "Both writes are versioned. A stale version is refused. Nothing is inferred from the names.",
    },
    {
      id: "warnings",
      title: "Why these failures are operationally dangerous",
      objective: "Recognise the ten prohibited shortcuts before they reach a live guest list.",
      instruction:
        "Duplicate materialisation creates two people for one allowance. Cross-household leakage shows the wrong family. Inferred titles and inferred gender or cultural status invent dignity the guest did not grant. Truncating Ẹ̀bùnolúwa to Ebun loses identity. Showing a child without a responsible adult fails safeguarding. Treating party membership as invitation or RSVP marks people as invited or attending who are not. Expanding S03 allowance invents hospitality the invitation did not grant. Treating this course as authority puts an unassigned person on a live event.",
      practice: "For each warning, name the first safe action if you see it happening.",
      feedback: "Stop, reload the approved projection, and use the governed action — or escalate. Do not patch identity in the browser.",
    },
  ],
  warnings: [
    {
      id: "duplicate-materialisation",
      title: "Do not duplicate people through companion materialisation",
      whyItFails: "A second named guest for one allowance invents a person who was never invited.",
      whatToDo: "Materialise once. A retry must resolve the same guest. If a second identity appears, stop and escalate.",
    },
    {
      id: "cross-household",
      title: "Do not leak across households or events",
      whyItFails: "Opening the wrong event or household shows private family links to the wrong staff.",
      whatToDo: "Stay inside the assigned event. A missing record is not-found, not a reason to search another event.",
    },
    {
      id: "inferred-title",
      title: "Do not infer a title",
      whyItFails: "Guessing Professor, Chief or Mrs from a name writes a dignity the guest did not supply.",
      whatToDo: "Leave honorific blank unless a title was given. Blank stays blank.",
    },
    {
      id: "inferred-gender-culture",
      title: "Do not infer gender or cultural status",
      whyItFails: "Gender and chieftaincy are not derived from given name, party role or relationship type.",
      whatToDo: "Record only declared structured fields. If unsure, leave the field empty.",
    },
    {
      id: "truncation",
      title: "Do not truncate names",
      whyItFails: "Cutting Ọmọ́tọ́lá or stripping diacritics loses the recorded identity.",
      whatToDo: "Keep the full Unicode name. Wrap by word. Never break character by character.",
    },
    {
      id: "child-without-adult",
      title: "Do not expose a child record without responsible-adult authority",
      whyItFails: "A child dossier without an active adult link is not ready and must not be treated as contactable.",
      whatToDo: "Link a responsible adult before treating the child as ready. Do not collect date of birth.",
    },
    {
      id: "party-is-not-invitation",
      title: "Party membership is not invitation truth",
      whyItFails: "Adding someone to an entourage does not issue an invitation.",
      whatToDo: "Use EOS-S03 invitation actions for invitation state. The party only records a declared grouping.",
    },
    {
      id: "party-is-not-rsvp",
      title: "Party membership is not RSVP truth",
      whyItFails: "A household party does not mark anyone as attending.",
      whatToDo: "Read RSVP from the S03 response. Never infer attendance from membership.",
    },
    {
      id: "s03-expansion",
      title: "Do not expand S03 companion authority",
      whyItFails: "Raising allowance above the invitation invents hospitality.",
      whatToDo: "Administer within the authorised quantity. Exception review is not a Planner action.",
    },
    {
      id: "course-is-not-authority",
      title: "Course completion is not operational authority",
      whyItFails: "A pass does not create an assignment or sign a gate.",
      whatToDo: "Keep working only where your Event OS assignment already allows it. Escalate for missing assignment.",
    },
  ],
  questions: [
    {
      id: "q-titled-adult",
      scenario: "titled-adult",
      paths: ALL,
      prompt: "You are recording Ọmọ́tọ́lá Ọlábọ́dé, who supplied the honorific Professor. What do you store?",
      options: [
        { id: "a", label: "Professor in the honorific field, with the given and family names kept separate." },
        { id: "b", label: "The full string Professor Ọmọ́tọ́lá Ọlábọ́dé as the given name." },
        { id: "c", label: "No honorific, because titles are inferred later for print." },
      ],
      correctOptionId: "a",
      remediation: "Titles are optional structured data. Store the supplied honorific; do not fold it into the name.",
    },
    {
      id: "q-formal-familiar",
      scenario: "formal-familiar",
      paths: ALL,
      prompt: "When may the directory show a confirmed formal salutation such as Professor Ọmọ́tọ́lá Ọlábọ́dé?",
      options: [
        { id: "a", label: "Whenever a preferred formal salutation was typed, even if addressing is unconfirmed." },
        { id: "b", label: "Only when addressing is confirmed and the preferred formal form was supplied." },
        { id: "c", label: "Whenever the honorific is Professor." },
      ],
      correctOptionId: "b",
      remediation: "Formal form is used after authorised confirmation. Familiar form stays the everyday display.",
    },
    {
      id: "q-blank-title",
      scenario: "blank-title",
      paths: ALL,
      prompt: "Adéṣínà has no honorific. What is the safe behaviour?",
      options: [
        { id: "a", label: "Leave the honorific blank and use a safe fallback. Do not invent Mr or Chief." },
        { id: "b", label: "Insert Mr because Adéṣínà is a masculine Yorùbá name." },
        { id: "c", label: "Copy the household principal’s title." },
      ],
      correctOptionId: "a",
      remediation: "Blank title remains blank. Gender and culture are not inferred from the name.",
    },
    {
      id: "q-child-dob",
      scenario: "child-no-dob",
      paths: ALL,
      prompt: "A child, Kọ́ládé, must be recorded. Which identity data is correct?",
      options: [
        { id: "a", label: "Full date of birth so catering can calculate age." },
        { id: "b", label: "Age band CHILD and a responsible-adult link. No date of birth." },
        { id: "c", label: "Age band only, marked ready even without an adult." },
      ],
      correctOptionId: "b",
      remediation: "Date of birth is forbidden. A child is not ready without a valid active adult link.",
    },
    {
      id: "q-household",
      scenario: "household",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "You create a HOUSEHOLD party for the Alákíjà family. What is true?",
      options: [
        { id: "a", label: "The household is one guest identity shared by everyone." },
        { id: "b", label: "The party is a container. Each member keeps an independent guest ID." },
        { id: "c", label: "Children inherit the principal’s invitation automatically." },
      ],
      correctOptionId: "b",
      remediation: "Household is a relationship container, never a substitute person or invitation.",
    },
    {
      id: "q-entourage",
      scenario: "entourage",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "An INVITATION_PARTY labelled “P09 entourage” is created from Adéṣínà’s dossier. Who is the principal?",
      options: [
        { id: "a", label: "Adéṣínà, because the party was opened from that dossier." },
        { id: "b", label: "Nobody, unless a principal guest was explicitly supplied." },
        { id: "c", label: "The first member added." },
      ],
      correctOptionId: "b",
      remediation: "Do not infer a principal from navigation. Supply one only when declared.",
    },
    {
      id: "q-independent-ids",
      scenario: "independent-identities",
      paths: ALL,
      prompt: "A party has two members. How many guest IDs must exist?",
      options: [
        { id: "a", label: "One guest ID for the party plus optional member names." },
        { id: "b", label: "Exactly two guest IDs, plus a distinct party ID that is not a guest." },
        { id: "c", label: "One guest ID reused for both people to keep the household together." },
      ],
      correctOptionId: "b",
      remediation: "Every represented person has a distinct guest ID. The party ID is not a person.",
    },
    {
      id: "q-issue-plus-one",
      scenario: "issue-entitlement",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "How is a plus-one issued in S04A?",
      options: [
        { id: "a", label: "Create a guest named Plus-One so the count looks right." },
        { id: "b", label: "Administer an unnamed companion entitlement on S03 authority. No guest is created yet." },
        { id: "c", label: "Add an empty member row to the household party." },
      ],
      correctOptionId: "b",
      remediation: "Unnamed allowance is a quantity on S03 authority. It is not a person.",
    },
    {
      id: "q-accept",
      scenario: "accept-entitlement",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "Accepting an available plus-one means which governed transition?",
      options: [
        { id: "a", label: "AVAILABLE toward NOMINATED or CONFIRMED, still without inventing a second principal." },
        { id: "b", label: "Creating two companion guests so the host can choose later." },
        { id: "c", label: "Marking the party RSVP as attending." },
      ],
      correctOptionId: "a",
      remediation: "Accept is a lifecycle transition. It does not mint extra people or change RSVP truth.",
    },
    {
      id: "q-decline",
      scenario: "decline-entitlement",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "The plus-one is declined. What must remain true?",
      options: [
        { id: "a", label: "Status DECLINED, no nominated guest ID, people count unchanged." },
        { id: "b", label: "A declined guest record is kept for the unused seat." },
        { id: "c", label: "The principal’s invitation is withdrawn." },
      ],
      correctOptionId: "a",
      remediation: "Declined unnamed allowance carries no guest. Invitation truth stays on S03.",
    },
    {
      id: "q-expire",
      scenario: "expire-entitlement",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "Expiring an unused allowance should do what?",
      options: [
        { id: "a", label: "Set EXPIRED and clear any unnamed guest fabrication. Retry later only if S03 still authorises it." },
        { id: "b", label: "Delete the principal guest so the seat cannot be reused." },
        { id: "c", label: "Convert the allowance into a household member." },
      ],
      correctOptionId: "a",
      remediation: "EXPIRED is a governed status. It does not delete people or invent members.",
    },
    {
      id: "q-revoke",
      scenario: "revoke-entitlement",
      paths: GOVERNORS.concat(["PLANNER"]),
      prompt: "Revoking a companion entitlement is allowed when the contract permits it. What is forbidden?",
      options: [
        { id: "a", label: "Recording REVOKED with a reason and audit." },
        { id: "b", label: "Using revoke to hide a child record from its responsible adult." },
        { id: "c", label: "Leaving the allowance unnamed after revoke where the projection says so." },
      ],
      correctOptionId: "b",
      remediation: "Revoke is an entitlement lifecycle action, not a way to bury a child identity.",
    },
    {
      id: "q-materialise-once",
      scenario: "materialise-once",
      paths: ALL,
      prompt: "You materialise Fọláṣadé Adékúnlé from an unnamed allowance. A network retry fires. What is correct?",
      options: [
        { id: "a", label: "Exactly one companion guest. The retry is idempotent and must not mint a second ID." },
        { id: "b", label: "Two guests named Fọláṣadé, then merge them later." },
        { id: "c", label: "Keep the unnamed allowance and also create Fọláṣadé." },
      ],
      correctOptionId: "a",
      remediation: "Materialisation creates or resolves exactly one guest. Retry must not duplicate.",
    },
    {
      id: "q-lineage",
      scenario: "preserve-lineage",
      paths: GOVERNORS.concat(["PLANNER"]),
      prompt: "After materialisation, what lineage must remain visible to an authorised role?",
      options: [
        { id: "a", label: "The companion guest ID, the entitlement, the S03 authority and the audit action." },
        { id: "b", label: "Only the familiar name; IDs are discarded for dignity." },
        { id: "c", label: "The household key as if it were the person." },
      ],
      correctOptionId: "a",
      remediation: "Lineage is the guest, entitlement and audit. Dignity does not mean deleting identifiers.",
    },
    {
      id: "q-title-amend",
      scenario: "title-correction",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "A supplied honorific was typed as Dr and must become Professor. How?",
      options: [
        { id: "a", label: "Governed addressing amend with expectedVersion, source and reason. Planner cannot confirm." },
        { id: "b", label: "Edit the directory label in the browser. Confirmation is optional." },
        { id: "c", label: "Infer Professor from the professional title field automatically." },
      ],
      correctOptionId: "a",
      remediation: "Title correction is a versioned amend. Confirmation is a separate permission.",
    },
    {
      id: "q-relationship-amend",
      scenario: "relationship-correction",
      paths: OPERATORS.concat(["CEO_OVERSIGHT"]),
      prompt: "A responsible-adult link was pointed at the wrong adult. What is the governed correction?",
      options: [
        { id: "a", label: "End the active link and create a new declared link. The child is blocked until the new link is active." },
        { id: "b", label: "Rename the adult’s guest record to the correct person." },
        { id: "c", label: "Add both adults to a household so either will do." },
      ],
      correctOptionId: "a",
      remediation: "Correct the relationship by ending and replacing the declared link. Do not overwrite another guest.",
    },
    {
      id: "q-planner-confirm",
      scenario: "planner-confirm",
      paths: ["PLANNER", "EVENT_DIRECTOR", "CEO_OVERSIGHT", "AUDITOR_READ_ONLY"],
      prompt: "May a Planner confirm addressing?",
      options: [
        { id: "a", label: "Yes, if they completed this course with distinction." },
        { id: "b", label: "No. Confirmation is a server-enforced permission. Hidden buttons are not authority." },
        { id: "c", label: "Yes, when the guest asked for a formal title." },
      ],
      correctOptionId: "b",
      remediation: "Planner administers capture. Confirmation stays with authorised roles. Course completion changes nothing.",
    },
    {
      id: "q-planner-expand",
      scenario: "s03-expansion",
      paths: ["PLANNER", "EVENT_DIRECTOR", "CEO_OVERSIGHT", "AUDITOR_READ_ONLY"],
      prompt: "A Planner types allowance 4 when S03 authorised 1. What happens?",
      options: [
        { id: "a", label: "The server refuses. S04A cannot expand S03 quantity." },
        { id: "b", label: "The write succeeds if the Planner passed ACA-S04A." },
        { id: "c", label: "Four unnamed guests are created so the print list looks full." },
      ],
      correctOptionId: "a",
      remediation: "Quantity authority stays on S03. Training never lifts that ceiling.",
    },
    {
      id: "q-auditor",
      scenario: "auditor-readonly",
      paths: ["AUDITOR_READ_ONLY", "CEO_OVERSIGHT", "EVENT_DIRECTOR"],
      prompt: "What may an Auditor do on S04A surfaces?",
      options: [
        { id: "a", label: "Read approved projections. Mutations are refused even if a control is visible." },
        { id: "b", label: "Correct titles so the audit trail looks tidy." },
        { id: "c", label: "Materialise companions to complete the file." },
      ],
      correctOptionId: "a",
      remediation: "Auditor is read-only. Server denial is the proof, not the absence of a button.",
    },
    {
      id: "q-course-authority",
      scenario: "course-not-authority",
      paths: ALL,
      prompt: "You scored 94% on ACA-S04A. Which statement is true?",
      options: [
        { id: "a", label: "You now have Event OS mutation rights on every event." },
        { id: "b", label: "You have distinction evidence only. Assignment and production approval are unchanged." },
        { id: "c", label: "Protected gates may be signed with this score." },
      ],
      correctOptionId: "b",
      remediation: AUTHORITY_DISCLAIMER,
    },
    {
      id: "q-cross-event",
      scenario: "cross-event",
      paths: GOVERNORS.concat(["PLANNER"]),
      prompt: "A guest URL from another event is pasted into the address bar. What is correct?",
      options: [
        { id: "a", label: "The server fails closed. Do not treat a 404 as permission to search another tenant." },
        { id: "b", label: "Open it anyway if you know the family." },
        { id: "c", label: "Copy the guest into the current event to be helpful." },
      ],
      correctOptionId: "a",
      remediation: "Cross-event access fails closed. Do not reconstruct another event’s household.",
    },
    {
      id: "q-no-body",
      scenario: "no-body-measure",
      paths: ALL,
      prompt: "Which field must never be collected on S04A guest intake?",
      options: [
        { id: "a", label: "Preferred display name." },
        { id: "b", label: "Full date of birth, body measurement or inferred gender." },
        { id: "c", label: "Optional pronunciation note where authorised." },
      ],
      correctOptionId: "b",
      remediation: "No unnecessary date of birth, body measurement or gender inference.",
    },
  ],
  authorityDisclaimer: AUTHORITY_DISCLAIMER,
});

export function acaS04AQuestionsFor(path: AcademyLearningPath) {
  return acaS04ACourse.questions.filter((question) => question.paths.includes(path));
}
