/* Generated by scripts/write-build-identity.mjs — placeholder for local typecheck; overwritten at build. */
export const BUILD_APPLICATION_SHA = "local-unreleased" as const;
export const BUILD_IDENTITY_SOURCE = "LOCAL_FALLBACK" as const;
export const BUILD_IDENTITY_CAPTURED_AT = "1970-01-01T00:00:00.000Z" as const;
