/* Generated by scripts/write-build-identity.mjs — do not edit by hand. */
export const BUILD_APPLICATION_SHA = "26aaf933fbc49866ca334d5feb205c0e63719c05" as const;
export const BUILD_IDENTITY_SOURCE = "GIT_REV_PARSE" as const;
export const BUILD_IDENTITY_CAPTURED_AT = "2026-09-17T17:23:19.336Z" as const;
