/* Generated by scripts/write-build-identity.mjs — do not edit by hand. */
export const BUILD_APPLICATION_SHA = "2c7b950593648b42e93a80fe681733ad441b64a0" as const;
export const BUILD_IDENTITY_SOURCE = "GIT_REV_PARSE" as const;
export const BUILD_IDENTITY_CAPTURED_AT = "2026-09-18T11:57:45.813Z" as const;
